CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS vector;

CREATE TYPE record_status AS ENUM ('active','disabled','archived','quarantined');
CREATE TABLE tenant (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, status record_status NOT NULL DEFAULT 'active', retention_days int NOT NULL DEFAULT 365, version int NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE app_user (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenant(id), oidc_subject text NOT NULL, email text NOT NULL, status record_status NOT NULL DEFAULT 'active', version int NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id,oidc_subject));
CREATE TABLE role (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenant(id), name text NOT NULL, permissions jsonb NOT NULL DEFAULT '[]', status record_status NOT NULL DEFAULT 'active', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id,name));
CREATE TABLE project (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenant(id), name text NOT NULL, status text NOT NULL DEFAULT 'draft', authorization jsonb, retention_days int NOT NULL DEFAULT 180, version int NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE authorized_asset (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenant(id), project_id uuid NOT NULL REFERENCES project(id), asset_type text NOT NULL, value text NOT NULL, criticality int NOT NULL DEFAULT 50 CHECK(criticality BETWEEN 0 AND 100), status record_status NOT NULL DEFAULT 'active', version int NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(project_id,asset_type,value));
CREATE TABLE scope_rule (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenant(id), project_id uuid NOT NULL REFERENCES project(id), rule_type text NOT NULL CHECK(rule_type IN ('allow','deny')), asset_type text NOT NULL, value text NOT NULL, source_classes jsonb NOT NULL DEFAULT '[]', status record_status NOT NULL DEFAULT 'active', version int NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE provider (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text UNIQUE NOT NULL, adapter_version text NOT NULL, source_class text NOT NULL, config jsonb NOT NULL DEFAULT '{}', status record_status NOT NULL DEFAULT 'disabled', version int NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE provider_credential_ref (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenant(id), provider_id uuid NOT NULL REFERENCES provider(id), vault_reference text NOT NULL, status record_status NOT NULL DEFAULT 'active', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE provider_capability (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), provider_id uuid NOT NULL REFERENCES provider(id), capability text NOT NULL, declaration jsonb NOT NULL, status record_status NOT NULL DEFAULT 'active', version int NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(provider_id,capability,version));
CREATE TABLE query_template (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), source_class text NOT NULL, provider text NOT NULL, category text NOT NULL, subcategory text, description text NOT NULL, input_schema jsonb NOT NULL, expected_evidence_type text NOT NULL, allowed_use text NOT NULL, source_reference text NOT NULL, status record_status NOT NULL DEFAULT 'quarantined', current_version int NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE query_version (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), query_template_id uuid NOT NULL REFERENCES query_template(id), version int NOT NULL, template text NOT NULL, normalized_hash text NOT NULL, quality_score numeric(4,3) NOT NULL, risk_baseline int NOT NULL, confidence_baseline numeric(4,3) NOT NULL, freshness text NOT NULL, requires_auth boolean NOT NULL DEFAULT true, immutable_created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(query_template_id,version));
CREATE TABLE query_tag (query_template_id uuid NOT NULL REFERENCES query_template(id), tag text NOT NULL, PRIMARY KEY(query_template_id,tag));
CREATE TABLE query_run (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenant(id), project_id uuid NOT NULL REFERENCES project(id), query_version_id uuid NOT NULL REFERENCES query_version(id), provider_id uuid NOT NULL REFERENCES provider(id), target text NOT NULL, status text NOT NULL, idempotency_key text NOT NULL, started_at timestamptz, completed_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id,idempotency_key));
CREATE TABLE raw_result (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenant(id), project_id uuid NOT NULL REFERENCES project(id), query_run_id uuid NOT NULL REFERENCES query_run(id), object_ref text NOT NULL, payload_hash text NOT NULL, status record_status NOT NULL DEFAULT 'active', retention_until timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE normalized_result (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenant(id), project_id uuid NOT NULL REFERENCES project(id), raw_result_id uuid NOT NULL REFERENCES raw_result(id), canonical_uri text NOT NULL, host text NOT NULL, content_hash text NOT NULL, observed_at timestamptz NOT NULL, status record_status NOT NULL DEFAULT 'active', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE entity (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenant(id), project_id uuid NOT NULL REFERENCES project(id), entity_type text NOT NULL, canonical_value text NOT NULL, attributes jsonb NOT NULL DEFAULT '{}', status record_status NOT NULL DEFAULT 'active', version int NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(project_id,entity_type,canonical_value));
CREATE TABLE entity_relationship (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenant(id), project_id uuid NOT NULL REFERENCES project(id), source_entity_id uuid NOT NULL REFERENCES entity(id), target_entity_id uuid NOT NULL REFERENCES entity(id), relationship_type text NOT NULL, score numeric(4,3) NOT NULL, signals jsonb NOT NULL, evidence_refs jsonb NOT NULL, analyst_confirmation text NOT NULL DEFAULT 'unreviewed', status text NOT NULL DEFAULT 'candidate', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE evidence (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenant(id), project_id uuid NOT NULL REFERENCES project(id), normalized_result_id uuid NOT NULL REFERENCES normalized_result(id), provider_id uuid NOT NULL REFERENCES provider(id), source_uri text NOT NULL, artifact_type text NOT NULL, object_ref text NOT NULL, content_hash text NOT NULL, redaction_state text NOT NULL, retention_class text NOT NULL, captured_at timestamptz NOT NULL, status record_status NOT NULL DEFAULT 'active', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE finding_cluster (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenant(id), project_id uuid NOT NULL REFERENCES project(id), canonical_key text NOT NULL, status text NOT NULL DEFAULT 'new', version int NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(project_id,canonical_key));
CREATE TABLE finding (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenant(id), project_id uuid NOT NULL REFERENCES project(id), cluster_id uuid REFERENCES finding_cluster(id), title text NOT NULL, category text NOT NULL, confidence numeric(4,3) NOT NULL, false_positive_probability numeric(4,3) NOT NULL, review_state text NOT NULL DEFAULT 'new', status text NOT NULL DEFAULT 'new', version int NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE finding_evidence (finding_id uuid NOT NULL REFERENCES finding(id), evidence_id uuid NOT NULL REFERENCES evidence(id), provenance jsonb NOT NULL, PRIMARY KEY(finding_id,evidence_id));
CREATE TABLE ai_model (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), provider text NOT NULL, model_id text NOT NULL, status record_status NOT NULL DEFAULT 'active', version int NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(provider,model_id,version));
CREATE TABLE ai_prompt_version (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, version int NOT NULL, schema jsonb NOT NULL, template_hash text NOT NULL, immutable_created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(name,version));
CREATE TABLE ai_run (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenant(id), project_id uuid NOT NULL REFERENCES project(id), finding_id uuid REFERENCES finding(id), model_id uuid NOT NULL REFERENCES ai_model(id), prompt_version_id uuid NOT NULL REFERENCES ai_prompt_version(id), evidence_refs jsonb NOT NULL, conclusion jsonb, concise_rationale text, status text NOT NULL, cost numeric(12,6) NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE risk_ruleset (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, version text NOT NULL, weights jsonb NOT NULL, overrides jsonb NOT NULL, immutable_created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(name,version));
CREATE TABLE risk_score (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenant(id), project_id uuid NOT NULL REFERENCES project(id), finding_id uuid NOT NULL REFERENCES finding(id), ruleset_id uuid NOT NULL REFERENCES risk_ruleset(id), factors jsonb NOT NULL, score numeric(5,2) NOT NULL, priority text NOT NULL, override_reason text, immutable_created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE report (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenant(id), project_id uuid NOT NULL REFERENCES project(id), report_type text NOT NULL, schema_version text NOT NULL, status text NOT NULL, version int NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE report_artifact (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenant(id), project_id uuid NOT NULL REFERENCES project(id), report_id uuid NOT NULL REFERENCES report(id), artifact_type text NOT NULL, object_ref text NOT NULL, content_hash text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE webhook (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenant(id), project_id uuid NOT NULL REFERENCES project(id), endpoint text NOT NULL, secret_ref text NOT NULL, event_types jsonb NOT NULL, status record_status NOT NULL DEFAULT 'active', version int NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE cost_event (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenant(id), project_id uuid NOT NULL REFERENCES project(id), provider text NOT NULL, unit text NOT NULL, quantity numeric(14,4) NOT NULL, amount numeric(14,6) NOT NULL, immutable_created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE audit_log (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenant(id), project_id uuid REFERENCES project(id), actor_id text NOT NULL, action text NOT NULL, resource_type text NOT NULL, resource_id text, outcome text NOT NULL, reason text, metadata jsonb NOT NULL DEFAULT '{}', previous_hash text, event_hash text NOT NULL, immutable_created_at timestamptz NOT NULL DEFAULT now());

CREATE INDEX ix_project_tenant ON project(tenant_id,status); CREATE INDEX ix_scope_project ON scope_rule(tenant_id,project_id,rule_type); CREATE INDEX ix_query_run_project ON query_run(tenant_id,project_id,status); CREATE INDEX ix_result_canonical ON normalized_result(tenant_id,project_id,canonical_uri); CREATE INDEX ix_result_hash ON normalized_result(tenant_id,project_id,content_hash); CREATE INDEX ix_evidence_lineage ON evidence(tenant_id,project_id,normalized_result_id); CREATE INDEX ix_finding_review ON finding(tenant_id,project_id,review_state); CREATE INDEX ix_ai_finding ON ai_run(tenant_id,project_id,finding_id); CREATE INDEX ix_risk_finding ON risk_score(tenant_id,project_id,finding_id); CREATE INDEX ix_audit_tenant_time ON audit_log(tenant_id,immutable_created_at DESC);

ALTER TABLE project ENABLE ROW LEVEL SECURITY; ALTER TABLE authorized_asset ENABLE ROW LEVEL SECURITY; ALTER TABLE scope_rule ENABLE ROW LEVEL SECURITY; ALTER TABLE query_run ENABLE ROW LEVEL SECURITY; ALTER TABLE raw_result ENABLE ROW LEVEL SECURITY; ALTER TABLE normalized_result ENABLE ROW LEVEL SECURITY; ALTER TABLE entity ENABLE ROW LEVEL SECURITY; ALTER TABLE entity_relationship ENABLE ROW LEVEL SECURITY; ALTER TABLE evidence ENABLE ROW LEVEL SECURITY; ALTER TABLE finding ENABLE ROW LEVEL SECURITY; ALTER TABLE finding_cluster ENABLE ROW LEVEL SECURITY; ALTER TABLE ai_run ENABLE ROW LEVEL SECURITY; ALTER TABLE risk_score ENABLE ROW LEVEL SECURITY; ALTER TABLE report ENABLE ROW LEVEL SECURITY; ALTER TABLE report_artifact ENABLE ROW LEVEL SECURITY; ALTER TABLE cost_event ENABLE ROW LEVEL SECURITY; ALTER TABLE audit_log ENABLE ROW LEVEL SECURITY;
DO $$ DECLARE t text; BEGIN FOREACH t IN ARRAY ARRAY['project','authorized_asset','scope_rule','query_run','raw_result','normalized_result','entity','entity_relationship','evidence','finding','finding_cluster','ai_run','risk_score','report','report_artifact','cost_event','audit_log'] LOOP EXECUTE format('CREATE POLICY tenant_isolation ON %I USING (tenant_id = nullif(current_setting(''app.tenant_id'', true), '''')::uuid) WITH CHECK (tenant_id = nullif(current_setting(''app.tenant_id'', true), '''')::uuid)',t); END LOOP; END $$;

REVOKE UPDATE, DELETE ON audit_log, risk_score, ai_prompt_version, query_version FROM PUBLIC;
